# Generated by Django 2.2.12 on 2020-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
