# Generated by Django 2.2.12 on 2020-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Preguntas'), ('Q', '¿Qué debo hacer?'), ('R', 'Mi resolución'), ('DC', 'Datos de contacto'), ('DP', 'Datos personales'), ('S', 'Saludo'), ('D', 'Despedida')], max_length=2, null=True),
        ),
    ]
