# Generated by Django 2.2.12 on 2020-05-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20200503_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
                ('translate_key', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('P', 'Pregunta'), ('T', 'Texto'), ('H', 'HTML'), ('PA', 'Pregunta Abierta'), ('PC', 'Pregunta cerrada'), ('PM', 'Pregunta múltiple'), ('PU', 'Pregunta única')], max_length=2, null=True)),
                ('section', models.ForeignKey(db_column='id_section', on_delete=django.db.models.deletion.PROTECT, to='session.Section')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
