# Generated by Django 2.2.12 on 2020-05-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20200503_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='help',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.AutoField(db_column='id_item', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id_choice', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('isCorrect', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('help', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('P', 'Pregunta'), ('T', 'Texto'), ('H', 'HTML'), ('PA', 'Pregunta Abierta'), ('PC', 'Pregunta cerrada'), ('PM', 'Pregunta múltiple'), ('PU', 'Pregunta única')], max_length=2, null=True)),
                ('item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.PROTECT, to='session.Item')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
