# Generated by Django 2.2.12 on 2020-05-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20200503_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('section__order', 'order')},
        ),
        migrations.AddField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
