# Generated by Django 2.2.12 on 2020-05-06 05:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('session', '0009_auto_20200506_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verse',
            old_name='id_section',
            new_name='id_verse',
        ),
    ]
